# Generated by Django 2.2.6 on 2019-10-31 20:07

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='col',
            field=models.IntegerField(validators=[game.models.validate_col_range]),
        ),
        migrations.AlterField(
            model_name='player',
            name='row',
            field=models.IntegerField(validators=[game.models.validate_row_range]),
        ),
        migrations.AlterField(
            model_name='player',
            name='tag',
            field=models.CharField(max_length=1, validators=[game.models.validate_unique_tag]),
        ),
    ]
